###################  项目启动端口  ###################
server:
  port: 8077
###################  spring配置  ###################
#spring:
#  redis:
#    host: localhost
#    port: 6379
#    password:
#  profiles:
#    active: dev
#  mvc:
#    static-path-pattern: /static/**
#    view:
#      prefix: /WEB-INF/view
#  http:
#    converters:
#      preferred-json-mapper: fastjson
#    multipart:
#      max-request-size: 100MB #最大请求大小
#      max-file-size: 100MB #最大文件大小
#  devtools:
#    restart:
#      enabled: false #是否开启开发者工具（true/false）
#      additional-paths: src/main/java
#      exclude: static/**,WEB-INF/view/**
#  aop:
#    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理